# Topic : Exception Handling NumPy - Pandas Basics

# Section A - Exception Handling

In [3]:
# 1. write a function safe_divide(a,b) that divides two numbers and handles ZeroDivisionError and 
# TypeError seperately , printing an appropriate message for each . use a finally block to print 
# "operation attempted . ' regardless of the outcome . test it with valid numbers , division by zero , and 
# a string input .

In [17]:
def safe_divide(a,b):
    try:
        result=a/b
        return result
    except ZeroDivisionError:
        return "Error: Division by zero is not allowed"
    except TypeError:
        return "Error: Both input must be number"      

In [18]:
print(safe_divide(30,4))
print(safe_divide(7,0))
print(safe_divide(10,'2'))

7.5
Error: Division by zero is not allowed
Error: Both input must be number


In [19]:
# 2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you define, inheriting from Exception)
# if age is negative or greater than 120.
# Catch this exception in a calling block and print a user-friendly message.
# Test it with at least 3 different values.

In [12]:
class InvalidAgeError(Exception):
    pass
    
def validate_age(age):
    if age < 0 or age > 120:        
        raise InvalidAgeError("age must be betn 0 to 120")
    print(f"valid age:{age}")

test=[25,-5,122]
for age in test:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print(f"Invalid Age Error:{e}")

valid age:25
Invalid Age Error:age must be betn 0 to 120
Invalid Age Error:age must be betn 0 to 120


In [13]:
# 3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
# e.g., user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it.

# Handle the following in a single try block using multiple except clauses:
# a) ValueError if the input is not a number.
# b) ZeroDivisionError if the input is zero.
# c) A generic Exception as a catch-all for anything else.
# Print the result if successful; otherwise print which error occurred.

In [16]:
user_input=['10','abc','0','5']
for val in user_input:
    try:
        num=int(val)
        res=100/num
        print(f"100/{num}={res}")
    except ValueError:
        print(f"ValueError: '{val}'mis not a valid number")
    except ZeroDivisionError:
        print(f"ZeroDivisionError: cannott divide ny zero")
    except Exception as e:
        print(f"Error:{e}")

100/10=10.0
ValueError: 'abc'mis not a valid number
ZeroDivisionError: cannott divide ny zero
100/5=20.0


# Section B — NumPy

In [ ]:
# 4. Create a 1D NumPy Array

# Create a 1D NumPy array of integers from 1 to 20. Perform the following:
# a) Reshape it into a 4 × 5 2D array.
# b) Print the sum of each row and each column.
# c) Extract all elements greater than 10 using boolean indexing.
# d) Replace all even numbers in the array with -1.

In [33]:
import numpy as np
a=np.arange(1,21)
print("array=>",a)

b=a.reshape(4,5) # array reshaping into 4*5 2D array
print("\n 4*5 2D reshaped array=>", b)

print("\n sum of each row:")
print(np.sum(b,axis=1))

print("\nSum of each column:")
print(np.sum(b,axis=0))

element=a[a>10]
print("\n element greater than 10:")
print(element) # element greater than 10 

a[a%2==0]=-1
print("\n array after replacing even numbers with -1")
print(a)



array=> [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 4*5 2D reshaped array=> [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 sum of each row:
[15 40 65 90]

Sum of each column:
[34 38 42 46 50]

 element greater than 10:
[11 12 13 14 15 16 17 18 19 20]

 array after replacing even numbers with -1
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [ ]:
# 5. Create two NumPy arrays A and B as shown below:

# A = np.array([[1, 2],[3, 4]])
# B = np.array([[5, 6],[7, 8]])

# Perform the following:

# a) Element-wise addition, subtraction, and multiplication.
# b) Matrix multiplication using np.dot() or the @ operator.
# c) Transpose of A.
# d) The determinant and inverse of A using np.linalg.

In [41]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print("\n Array A=>",A)
print("\n Array B=>",B)
print("\n addition of A & B=>",A+B)
print("\n subtraction of A & B=>",A-B)
print("\n multiplication of A & B=>",A*B)

print("\n matrix multiplication:")
print(np.dot(A,B))

print("\n transpose of A=>",A.T)

print("determinant of A=>",np.linalg.det(A))
print("inverse of A=>",np.linalg.inv(A))



 Array A=> [[1 2]
 [3 4]]

 Array B=> [[5 6]
 [7 8]]

 addition of A & B=> [[ 6  8]
 [10 12]]

 subtraction of A & B=> [[-4 -4]
 [-4 -4]]

 multiplication of A & B=> [[ 5 12]
 [21 32]]

 matrix multiplication:
[[19 22]
 [43 50]]

 transpose of A=> [[1 3]
 [2 4]]
determinant of A=> -2.0000000000000004
inverse of A=> [[-2.   1. ]
 [ 1.5 -0.5]]


In [58]:
np.random.seed(42)
a=np.random.randint(1,100,15)
print("array of 15 integer betweeen 1 and 100:",a)

print("\n mean =>",np.mean(a))
print(" median =>",np.median(a))
print(" standard deviation =>",np.std(a))
print(" minimum =>",np.min(a))
print(" maximum =>",np.max(a))

sorted_array=np.sort(a)[::-1]
print("\n array in descending order:",sorted_array)

large_3_indices=np.argsort(a)[-3:]
print("\n indices of 3 largest values",large_3_indices)

normalized_arr = (a - np.min(a)) / (np.max(a) - np.min(a))
print("\nNormalized Array:\n",normalized_arr)


array of 15 integer betweeen 1 and 100: [52 93 15 72 61 21 83 87 75 75 88 24  3 22 53]

 mean => 54.93333333333333
 median => 61.0
 standard deviation => 29.42666968735825
 minimum => 3
 maximum => 93

 array in descending order: [93 88 87 83 75 75 72 61 53 52 24 22 21 15  3]

 indices of 3 largest values [ 7 10  1]

Normalized Array:
 [0.54444444 1.         0.13333333 0.76666667 0.64444444 0.2
 0.88888889 0.93333333 0.8        0.8        0.94444444 0.23333333
 0.         0.21111111 0.55555556]


# Section C — Pandas Basics

In [59]:
# 7. Create a Pandas DataFrame from the dictionary below and perform the following:
# data = {
#    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
#    "Age": [23, 21, 25, 22, 24],
#    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
#   "Score": [88, 92, 79, 95, 67]
#  }

# a) Display the first 3 rows and the data types of each column.
# b) Add a new column Grade based on Score:
# Score ≥ 90 → 'A'
# Score ≥ 75 → 'B'
# Else → 'C'

# c) Sort the DataFrame by Score in descending order.
# d) Filter rows where Department is 'AI'.

In [17]:
import pandas as pd

data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

print("First 3 Rows:")
print(df.head(3))
print("\nData Types:")
print(df.dtypes)

def grade(score):
    if score >= 90:
        return 'A'
    elif score >= 75:
        return 'B'
    else:
        return 'C'

df["Grade"] = df["Score"].apply(grade)
print("\nDataFrame with Grade:")
print(df)

sorted_df = df.sort_values(by="Score", ascending=False)
print("\nSorted by Score (Descending):")
print(sorted_df)

ai_df = df[df["Department"] == "AI"]
print("\nEmployees in AI Department:")
print(ai_df)

First 3 Rows:
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types:
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with Grade:
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by Score (Descending):
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

Employees in AI Department:
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [13]:
# 8. Using the same DataFrame from Q7
# a) Group by Department and find the average Score for each.
# b) Find the row with the highest Score using idxmax().
# c) Rename the column Score to Marks.
# d) Drop the Age column and display the resulting DataFrame.

In [18]:

print(df.groupby("Department")["Score"].mean()) # Average Score by Department
print("\n")

print(df.loc[df["Score"].idxmax()]) # Row with highest Score
print("\n")

df.rename(columns={"Score": "Marks"}, inplace=True) # Rename Score to Marks
print("\n")
print(df)

df.drop("Age", axis=1, inplace=True) # Drop Age column
print("\n")
print(df)

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64


Name            Meera
Age                22
Department    Web Dev
Score              95
Grade               A
Name: 3, dtype: object




    Name  Age    Department  Marks Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C


    Name    Department  Marks Grade
0  Aarav            AI     88     B
1  Priya  Data Science     92     A
2  Karan            AI     79     B
3  Meera       Web Dev     95     A
4  Sahil  Data Science     67     C


In [64]:
# 9. Create a DataFrame with some missing values as shown below and handle them:
# import numpy as np
# data = {
#   "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
#   "Price": [10, np.nan, 5, 8, np.nan],
#   "Stock": [100, 50, np.nan, 30, 20]
# }

# a) Check the number of missing values in each column using isnull().sum().
# b) Fill missing Price values with the column mean.
# c) Drop rows where Stock is still missing.
# d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index.

In [22]:
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

print(df.isnull().sum())# Count missing values

df['Price']=df["Price"].fillna(df["Price"].mean())#  Fill missing Price values with mean

df.dropna(subset=["Stock"], inplace=True)#  Drop rows where Stock is missing

df.to_csv("cleaned_products.csv", index=False)#  Save to CSV

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


In [66]:
# 10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
# a) Print its shape and column names.
# b) Add a new column Total_Value as: => Price * Stock
# c) Use describe() to print summary statistics of the numeric columns.
# d) Wrap the file reading step in a try-except block to handle the case where the file does not exist (FileNotFoundError).

In [24]:
import pandas as pd

try:
    df = pd.read_csv("cleaned_products.csv")

    print("Shape:", df.shape)    # Sshape

    print("Columns:", df.columns.tolist()) # columns

    df["Total_Value"] = df["Price"] * df["Stock"]   #  Add Total_Value column

    print(df)

    print(df.describe())     # Summary statistics

except FileNotFoundError:
    print("Error: cleaned_products.csv file not found.")

Shape: (4, 3)
Columns: ['Product', 'Price', 'Stock']
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
