# NumPy => 15-jun

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
# CREATING ARRAY

In [5]:
sample_array=np.array([1,2,3,4])

In [7]:
sample_array

array([1, 2, 3, 4])

In [8]:
array_1=np.array([4,5,7,8])

In [9]:
array_1

array([4, 5, 7, 8])

In [10]:
# 2D Array (a matrix) with 2 rows and 2 columns

In [13]:
sample_array_2=np.array([[1,2],[3,4]])

In [15]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [17]:
a1=np.array([[45,67,89],[23,43,12]])

In [18]:
a1

array([[45, 67, 89],
       [23, 43, 12]])

# 3D Tensor (2 Matrices , each with 2 rows & 2 columns)

In [22]:
sample_tensor_3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [23]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
s1=np.array([[[12,34],[45,87]],[[23,65],[21,76]]])

In [25]:
s1

array([[[12, 34],
        [45, 87]],

       [[23, 65],
        [21, 76]]])

# Dimentions 

In [26]:
# 0-D Array(scalar) => 5 (only one element)
# 1-D Array(vector) => [1,2,3,4] 
# 2-D Array(Matrix) => (rows and columns)
# 3-D Array(tensor) => (page,row,column)

# Properties of array

In [32]:
sample_array=np.array([[2,4,6],[7,8,9]])

In [33]:
sample_array

array([[2, 4, 6],
       [7, 8, 9]])

In [34]:
# shape => to access hoe many numbers of rows and columns

In [35]:
sample_array.shape 

(2, 3)

In [36]:
# dimentions => to access diemntions

In [37]:
sample_array.ndim

2

In [38]:
# Size => to acess total elements

In [39]:
sample_array.size

6

In [40]:
 # dtype => to check data type

In [41]:
sample_array.dtype

dtype('int64')

In [ ]:
# create 3D array and use above attributes 

In [55]:
sample_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [56]:
sample_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# shape 

In [58]:
sample_array.shape

(2, 2, 3)

In [ ]:
# dimentions

In [57]:
sample_array.ndim

3

In [ ]:
# size

In [59]:
sample_array.size

12

In [ ]:
# data type

In [60]:
sample_array.dtype

dtype('int64')

# special arrays

In [51]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Arange(start=0,top=10,step=2)

In [66]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [67]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [68]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# indexing 

In [73]:
sample_array=np.array([10,20,30,40])

In [74]:
sample_array

array([10, 20, 30, 40])

In [75]:
sample_array[0]

np.int64(10)

In [76]:
sample_array[2]

np.int64(30)

In [77]:
sample_array[-1]

np.int64(40)

# slicing

In [78]:
sample_array[1:3]

array([20, 30])

# Array Operation

In [79]:
a=np.array([1,2,3,4,5])

In [80]:
b=np.array([6,7,8,9,10])

In [81]:
a

array([1, 2, 3, 4, 5])

In [82]:
b

array([ 6,  7,  8,  9, 10])

In [83]:
a+b

array([ 7,  9, 11, 13, 15])

In [84]:
a-b

array([-5, -5, -5, -5, -5])

In [85]:
a*b

array([ 6, 14, 24, 36, 50])

In [86]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
# example

In [87]:
array1=np.array([12,34,56])

In [88]:
array2=np.array([34,67,89])

In [89]:
array1+array2

array([ 46, 101, 145])

In [92]:
array1-array2

array([-22, -33, -33])

In [93]:
array1*array2

array([ 408, 2278, 4984])

In [94]:
array1/array2

array([0.35294118, 0.50746269, 0.62921348])

# mathematical functions

In [95]:
sample_array=np.array([1,4,9])

In [96]:
sample_array

array([1, 4, 9])

In [97]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [98]:
s1=np.array([64,81,49])

In [100]:
np.sqrt(s1)

array([8., 9., 7.])

In [101]:
np.exp(3)

np.float64(20.085536923187668)

In [102]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [103]:
np.exp(8)

np.float64(2980.9579870417283)

In [104]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [105]:
np.log(67)

np.float64(4.204692619390966)

# statistical functions

In [106]:
sample_array=np.array([1,2,3,4,5])

In [107]:
sample_array

array([1, 2, 3, 4, 5])

In [108]:
np.mean(sample_array)

np.float64(3.0)

In [109]:
np.median(sample_array)

np.float64(3.0)

In [112]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [113]:
np.min(sample_array)

np.int64(1)

In [114]:
np.max(sample_array)

np.int64(5)

# Array reshaping 

In [125]:
sample_array=np.arange(6)

In [126]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [127]:
# 2D array

In [128]:
r=sample_array.reshape(2,3)

In [129]:
r

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
# flattening of array

In [131]:
s=np.array([[2,3],[4,5]])

In [132]:
s

array([[2, 3],
       [4, 5]])

In [134]:
s.flatten()

array([2, 3, 4, 5])

In [141]:
sample_array=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [143]:
sample_array.ndim

3

In [144]:
sample_array.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
# joining arrays

In [146]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [147]:
np.concat((a,b))

array([1, 2, 3, 4, 5, 6])

In [149]:
# slitting arrays

In [150]:
sample_array=np.array([1,2,3,4])

In [151]:
sample_array

array([1, 2, 3, 4])

In [ ]:
# second parameter=> divide into no of parts

In [152]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [153]:
np.split(sample_array,2)

[array([1, 2]), array([3, 4])]

# random modules

In [157]:
np.random.rand(3)

array([0.98646403, 0.34553369, 0.19909849])

In [158]:
np.random.randint(1,10,5)

array([6, 6, 4, 7, 6], dtype=int32)

# Axis concept

In [172]:
s=np.array([[2,3],[4,5]])

In [173]:
s

array([[2, 3],
       [4, 5]])

In [ ]:
# row wise and column wise sum

In [164]:
np.sum(s,axis=0)

array([6, 8])

In [ ]:
# 1 row & 1 column sum

In [165]:
np.sum(s,axis=1)

array([5, 9])

In [166]:
# NaN & missing values

In [167]:
s=np.array([1,np.nan,3,])

In [168]:
s

array([ 1., nan,  3.])

In [169]:
np.isnan(s)

array([False,  True, False])

In [174]:
# create 2 numpy arrays and perform element wise additon , subtraction ,mulplication
# & modulus operation

In [175]:
a=np.array([2,3,4,6])
b=np.array([6,7,8,9])

In [181]:
print("addition=>",a+b)

addition=> [ 8 10 12 15]


In [182]:
print("subtraction=>",a-b)

subtraction=> [-4 -4 -4 -3]


In [183]:
print("multiplication=>",a*b)

multiplication=> [12 21 32 54]


In [184]:
print("division=>",a/b)

division=> [0.33333333 0.42857143 0.5        0.66666667]


In [185]:
print("modulus=>",a%b)

modulus=> [2 3 4 6]
